apiVersion: v1
kind: Service
metadata:
  name: azuredctsp-web
  labels:
    app: azuredctsp-web-label
spec:
  ports:    
    - port: 80
      targetPort: 80
  selector:
    app: azuredctsp-web-pod
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: azuredctsp-apiserver
  labels:
    app: azuredctsp-apiserver-label
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: azuredctsp-apiserver-pod-label-app
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: azuredctsp-web-pod
  labels: 
    name: azuredctsp-web-pod
    app: azuredctsp-web-pod
spec:
  hostname: webclient
  containers: 
   - name: webclient-nano
     image: uday31in/azuredctsp-web
     ports:
      - containerPort: 80
        name: http
        protocol: TCP
     env: 
      - name: azuredctsp_port
        value: "80"
      - name: ASPNETCORE_apiserverurl
        value: "http://azuredctsp-apiserver.default.svc.cluster.local/calculate"
---
apiVersion: v1
kind: Pod
metadata:
  name: azuredctsp-apiserver-pod
  labels: 
    name: azuredctsp-apiserver-pod-label-name
    app: azuredctsp-apiserver-pod-label-app
spec:
  hostname: apiserver
  containers: 
    - name: apiserver
      image: uday31in/azuredctsp-apiserver
      ports:
       - containerPort: 80
         name: api
         protocol: TCP

