version: '3'

services:
  azuredctsp:
    image: azuredctsp-web
    build:
      context: .
      dockerfile: azuredctsp/Dockerfile
    environment:
      - ASPNETCORE_apiserverurl=http://azuredctsp-api
  azuredctsp-api:
    image: uday31in/azuredctsp-apiserver
    