version: '3'
services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0.3
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./azuredctsp.sln && dotnet publish ./azuredctsp.sln -c Release -o ./obj/Docker/publish"