version: '3'

services:
  azuredctsp:
    image: azuredctsp-web
    build:
      context: ./azuredctsp
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_apiserverurl=http://52.168.169.234/calculate
  azuredctsp-api:
    image: azuredctsp-apiserver
    