replicaCount: 1
restartPolicy: Never

image:
  repository: uday31in/azuredctsp-web
  tag: latest
  pullPolicy: Always

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: LoadBalancer
  port: 80
  nodePort: ""

podAnnotations: {}

resources: {}

nodeSelector: {}