
apiVersion: v1
kind: Service
metadata:
  name: azuredctsp-web
  labels:
    app: azuredctsp-web-label
  annotations:
    external-dns.alpha.kubernetes.io/hostname: aci-web.k8.uday365.com
spec:
  ports:    
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    app: azuredctsp-web-pod
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: azuredctsp-apiserver
  annotations:
        external-dns.alpha.kubernetes.io/hostname: aci-api.k8.uday365.com
  labels:
    app: azuredctsp-apiserver-label
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  selector:
    app: azuredctsp-apiserver-pod
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: azuredctsp-web-deployment
spec: 
  replicas: 1
  template: 
    metadata:
      labels: 
        app: azuredctsp-web-pod
        role: website
        tier: frontend
    spec: 
      containers: 
      - name: webclient-nano
        resources:
          requests:
            memory: 1G
            cpu: 1
        image: uday31in/azuredctsp-web
        env: 
          - 
            name: azuredctsp_port
            value: "80"
          - 
            name: ASPNETCORE_apiserverurl
            value: "http://azuredctsp-apiserver.default.svc.cluster.local"
        ports: 
          - 
            containerPort: 80
            name: http
            protocol: TCP
      dnsPolicy: ClusterFirst
      nodeName: virtual-kubelet-uday-k8-aci-linux
      tolerations:
      - key: azure.com/aci
        effect: NoSchedule
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: azuredctsp-apiserver
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: azuredctsp-apiserver-pod
        role: webapi
        tier: backend
    spec: 
      containers: 
        - image: uday31in/azuredctsp-apiserver
          imagePullPolicy: Always
          name: apiserver
          resources:
            requests:
              memory: 1G
              cpu: 1
          ports: 
            - 
              containerPort: 80
              name: api
              protocol: TCP
      dnsPolicy: ClusterFirst
      nodeName: virtual-kubelet-uday-k8-aci-linux
      tolerations:
      - key: azure.com/aci
        effect: NoSchedule
