--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: azuredctsp-web-api-deployment
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: azuredctsp-web-pod
        role: website
        tier: frontend
    spec: 
      containers: 
        - 
          env: 
            - 
              name: azuredctsp_port
              value: "80"
            - 
              name: ASPNETCORE_apiserverurl
              value: "http://localhost:8080"
          image: uday31in/azuredctsp-web
          name: webclient-nano
          ports: 
            - 
              containerPort: 80
              name: http
              protocol: TCP
          resources: 
            requests: 
              cpu: 1
              memory: 1G
        - 
          env: 
            - 
              name: SERVER_PORT
              value: "8080"
          image: uday31in/azuredctsp-apiserver
          imagePullPolicy: Always
          name: frontend
          ports: 
            - 
              containerPort: 8080
              name: api
              protocol: TCP
          resources: 
            requests: 
              cpu: 1
              memory: 1G
      dnsPolicy: ClusterFirst
      nodeName: virtual-kubelet-beamwork-linux
      tolerations: 
        - 
          effect: NoSchedule
          key: azure.com/aci
